### ISSUE TITLE
Game crashes on startup (Starfield)

### ISSUE THREAD

**Issue by Boeblahoebla** [RoseTheFlower/UltrawideIndex#54] opened 2023-09-08 09:51 UTC
Hi m8...

First of all nice work on this mod. I couldn't get it working though...

![image](https://github.com/RoseTheFlower/UltrawideIndex/assets/55714738/32721961-fa8f-435f-9731-1ee8d490af19)

I'm running the Gamepass version

**Comment by jvmesa** [comment] 2023-09-08 14:14
Exactly the same here. W11, Gamepass version. The start return to normal removing the files. Thanks.

**Comment by RoseTheFlower** [comment] 2023-09-08 18:37
Do you use a DLSS mod? I think having that tends to result in crashes for people, but it's worth trying to rename winmm to version or vice versa.

**Comment by Krashlog** [comment] 2023-09-08 20:36
> Do you use a DLSS mod? I think having that tends to result in crashes for people, but it's worth trying to rename winmm to version or vice versa.

Yeah, I'm not sure if it works with DLSS... there are two versions to download, I guess we need to use the DLSS version if we use this mod?

https://www.nexusmods.com/starfield/mods/196

I'm not sure how the DLL injection works, can they both be used together since they both use winmm.dll to inject themselves? What's that about renaming "winmm" to "version"? Sorry if those questions have been answered elsewhere, can't find anything in the README.

**Comment by RoseTheFlower** [comment] 2023-09-08 20:42
I don't know anything about the injection process of the paid DLSS 3 mod either. For one person, having the DLL of my archive named `version` helped with the incompatibility, while for another person it was having it named `winmm`, hence the separate archives I'm offering.

The free DLSS 3 mod you linked uses the same loader as I did, so there should be no difference in whether you use their winmm.dll or the one of my archive. You shouldn't have both `version` and `winmm` in the folder at once.

From there, I think any crashes would have to be related to those DLSS mods unless someone runs my mod without anything else and can document a more or less reproducible path to the crash.

**Comment by RoseTheFlower** [comment] 2023-09-08 20:50
Also keep in mind that the FSR2 bridge won't work or will crash the game on launch unless you also have a DLSS / XESS dll in your folder, but that is completely unrelated to my fix.

**Comment by Krashlog** [comment] 2023-09-08 22:00
Thanks, it works perfectly with the DLSS mod I linked (and of couse the required Nvidia dlls, of course).

**Comment by RoseTheFlower** [comment] 2023-09-08 22:55
@Boeblahoebla @jvmesa  Try my updated archive for DLSS. I think the culprit was a missing .ini override, now included in the archive.

**Comment by jvmesa** [comment] 2023-09-09 12:08
Thanks @RoseTheFlower! This last DLSS version works like a charm. Compared to the ".ini tunning" method, I have improve FPS performance from 55 to 75 FPS (in average). I'm not using DLSS mod. Also FOV, using the same value, looks now more "natural" , I think (call me fool). Something I need to compare later. (MS Gamepass, RTX 3080, Samsung Odyssey G9)

**Comment by jvmesa** [comment] 2023-09-09 20:29
After playing a couple of hours, it seems the FPS increasement was just an illusion. The rest is stable, and I see just a disappointing missed aspect ratio when you are interacting with the robot to share equipment and resources. Here you have it:

**Normal Inventory** 
![Starfield 09_09_2023 22_17_46](https://github.com/RoseTheFlower/UltrawideIndex/assets/108762975/7dbd5f91-2400-4307-b90b-f7ba34c2b6ca)

**Vasco Inventory**
![Starfield 09_09_2023 22_16_59](https://github.com/RoseTheFlower/UltrawideIndex/assets/108762975/11758893-6166-44a8-96ff-143179fb5df7)

Just wondering if you have noticed this.

Good work and best regards.

**Comment by RoseTheFlower** [comment] 2023-09-09 20:51
Yep, the 3D models at the shop, crafting and safe screens are squished because of the photo mode fix. I haven't found a way to address the issue yet.

**Comment by RoseTheFlower** [comment] 2023-09-10 07:30
The latest version of my solution contains a fix for those 3D preview issues @jvmesa.

**Comment by jvmesa** [comment] 2023-09-10 14:07
Uhmm. @RoseTheFlower, unfortunately this is still looking bad. This is the "Vasco" view this morning, after installing the new .asi : 

![Starfield 10_09_2023 15_58_27](https://github.com/RoseTheFlower/UltrawideIndex/assets/108762975/de6fe6e4-54aa-4cdd-9f2d-dc5c776c71a7)

**Comment by RoseTheFlower** [comment] 2023-09-10 19:01
> Uhmm. @RoseTheFlower, unfortunately this is still looking bad. This is the "Vasco" view this morning, after installing the new .asi :

Are you sure that is with v1.2 and your exe untouched? I tested it as extensively as I could given my progression, then two other users tested it successfully as well.

**Comment by jvmesa** [comment] 2023-09-10 20:00
> > Uhmm. @RoseTheFlower, unfortunately this is still looking bad. This is the "Vasco" view this morning, after installing the new .asi :
> 
> Are you sure that is with v1.2 and your exe untouched? I tested it as extensively as I could given my progression, then two other users tested it successfully as well.

Excuse me @RoseTheFlower , it was just me doing stupids things. Indeed 1.2 version works well with the shop issue. Thanks. :)

**Comment by soulcr4ft** [comment] 2023-09-11 16:06
> The latest version of my solution contains a fix for those 3D preview issues @jvmesa @soulcr4ft

Thank you, the squished 3D previews are fixed indeed! I still have one weird thing in the game, the textboxes when playing at 32:9 are massive, the command prompt for fast travel, the outpost text box guide, the plaques that you interact and give you information, etc., sometimes you can't even see the whole thing in the screen, like in the example below, if you can make them look normal it would be awesome. Other nice improvements would be to expand the vignette effect on the scanner to cover the whole screen and the scopes that use the blackout effect cover the whole borders too. Don't know if you can fix those or even it they are possible to solve with the mod, but thank you again for the hard work making the game better.

![Starfield 2023-09-10 18-03-16](https://github.com/RoseTheFlower/UltrawideIndex/assets/144563851/d5582226-c626-4431-bb81-e2c88f699066)
![Starfield 2023-09-10 16-21-34](https://github.com/RoseTheFlower/UltrawideIndex/assets/144563851/5fe7dc42-7709-49b2-bedd-2ca1edd12daf)
![Starfield 2023-09-11 13-02-59](https://github.com/RoseTheFlower/UltrawideIndex/assets/144563851/3f251fba-5a22-4b31-8a08-8b5e61686902)

**Comment by miaXcova** [comment] 2023-09-12 11:23
1.3 made initial screen black.  Reverted to 1.2 and back to normal.  Only issue I have to report was the outpost build screen has the outpost info at the lower right of the screen chopped.  Playing at 5760x1080 (1920x1080x3).  Thanks for all your work Rose!

**Comment by Boeblahoebla** [comment] 2023-09-12 16:07
Hi thx for reply... Sorry for my late one.

Indeed it works. It no longer crashes, but there are still 3 issues I am facing:
- Menu's too big
- I can't use a weapon with a scope or the game crashes
- Object previews in inventory are vertically stretched

Apart from that all works as intended. Thx again for all your hard work

**Comment by Boeblahoebla** [comment] 2023-09-12 16:11
> e, the command prompt for fast travel, the outpost text box guide, the plaques that you interact and give you information, etc., sometimes you can't even see the whole thing in the screen, like in the example below, if you can make them look normal it would be awesome. Other nice improvements would be to expand the vignette effect on the scanner to cover the whole screen and the scopes that use the blackout effect cover the whole bo

I have the same setup :-) 3* 1080p

**Comment by RoseTheFlower** [comment] 2023-09-13 03:34
> Indeed it works. It no longer crashes

Great! Closing this specific issue but we can still discuss other things in this thread or have a new one.

>I can't use a weapon with a scope or the game crashes

The scope doesn't crash the game on my end when testing with a MagSniper at 48:9. The mod has no code specific to those screens, so it could be from another mod you have installed or even the game itself.

>Object previews in inventory are vertically stretched

The inventory previews aren't stretched on my end. Make sure your exe is untouched.

![image](https://github.com/RoseTheFlower/UltrawideIndex/assets/4759227/8dcd7081-cbc3-460c-9275-18d6f10778f0)

>Menu's too big

I'm not seeing the issue of big menus either (the inventory is fine, as seen above), unless you mean the same thing as reported by soulcr4ft, which affects prompts and perhaps things like elevator menus.

I will look more into the scopes but at the moment I see no way to addressing the game spanning some screens.

**Closed by RoseTheFlower** 2023-09-13 03:34 UTC

**Comment by Boeblahoebla** [comment] 2023-09-16 21:34
Yes I was referring to the post of soulcr4ft. The in game menu prompts are way to big & indeed like in the upper picture the top line sometimes can't be read.
